version: "3.9"

services:

  amora-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amora-api
    env_file:
      - .env
    environment:
      - ENABLE_WHATSAPP_BOT=false
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  amora-whatsapp:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: amora-whatsapp
    env_file:
      - .env
    environment:
      - ENABLE_WHATSAPP_BOT=true
    restart: unless-stopped
