FROM ghcr.io/puppeteer/puppeteer:18

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
ENV PUPPETEER_SKIP_DOWNLOAD=true

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

CMD ["node", "whatsapp/bot.js"]
